CREATE INDEX ON SUPERVISOR(CPF);

CREATE INDEX ON VENDEDOR(Codigo);

CREATE INDEX ON SECRETARIO(CPF);

CREATE INDEX ON ESTOQUISTA(CPF);

CREATE INDEX ON ENTREGADOR(CPF);

CREATE INDEX ON CAMINHAO(Placa);

CREATE INDEX ON CLIENTE(CPF);

CREATE INDEX ON MERCADORIA(Codigo);

CREATE INDEX ON VENDA(Codigo);

CREATE INDEX ON CIDADES_VENDEDOR(CPFVendedor);

CREATE INDEX ON CONTROLA_MERCADORIA(CodMercadoria);

CREATE INDEX ON INFORMA_ENTREGADOR(CPFEstoquista);

CREATE INDEX ON SECRETARIO_ESTOQUISTA_VENDA(CPFEstoquista);

CREATE INDEX ON TELEFONE_CLIENTE(Telefone);

CREATE INDEX ON TELEFONE_ENTREGADOR(Telefone);

CREATE INDEX ON TELEFONE_ESTOQUISTA(Telefone);

CREATE INDEX ON TELEFONE_SECRETARIO(Telefone);

CREATE INDEX ON TELEFONE_SUPERVISOR(Telefone);

CREATE INDEX ON TELEFONE_VENDEDOR(Telefone);

CREATE INDEX ON TEM_MERCADORIA(CodVenda);

CREATE INDEX ON USA_CAMINHAO(PlacaCaminhao);


